[stat_parameters]
datatype = log
highly_variable = True
# Test only 10 genes, ideally we would also be able to suply a list genes to test
n_highly_variable = 10 
label = CLONE
num_shuffles = 1000
remove_immune_receptors = False
normalize = True
filterCells = True
onlyClones = True
[IO]
# Rename to something more descriptive (e.g. scanpy_object)
CountsFile = ../data/CombinedDivision.h5ad
# TODO: user should be able to specify output name and location, or just better handling of paths so it need not be run in the directory
out_dir = ../outputs/
